version: '3'
services:
  master:
    image: mysql:debian
    restart: always
    ports:
      - 3321:3306
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=bd_medicamentos
    command: --default-time-zone='America/La_Paz'